language: android
env:
  global:
  - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"
  - secure: FeDzaUloNC2A8G2v2Z5B1kx5kizTWGELnimtYeFO8VfYk+WVtvS+6dRfZN2whp0GxYJIvGr//6cnodxAUr039cXROm3zVXZu1/G7cHtJkb89/DGcKmIOaolWZ9BnggqdYTNU7xYoA0T7HNH5ILFs41L2f60rOBVzMMrEvzb8VfY=
  - secure: VJYe/hgudROET8hXZwB4LlhE+hlIW6R+rt9ieWBAruLlH+Udl+dRBhq3d9Vh36ImqslgSP6yZsyk3Ey7mdSgdkFu70bF1WHs925D/DVSEtByIpMEINJ/pEFFajJOk1p54kxVxhGg0gBzD8hFhPb3FoeG/8MTF31s0aahJqmPEgI=
jdk: oraclejdk8
android:
  components:
  - tools
  - tools
  - platform-tools
  - android-24
  - build-tools-24.0.2
before_install:
- if [ -n "$GPG_PASS" ]; then echo $GPG_PASS | gpg --passphrase-fd 0 local.properties.gpg;
  fi
- if [ -n "$GPG_PASS" ]; then echo $GPG_PASS | gpg --passphrase-fd 0 settings/service_account.json.gpg;
  fi
- if [ -n "$GPG_PASS" ]; then echo $GPG_PASS | gpg --passphrase-fd 0 settings/release.keystore.gpg;
  fi
- if [ -z "$GPG_PASS"]; then touch local.properties; fi
after_success:
- if [ -n "$GITHUB_API_KEY" ]; then .buildscript/deploy_google_play.sh; fi
script: "./gradlew check"
branches:
  except:
  - gh-pages
